name: Build Extension Releases

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set tag name
        id: set_tag_name
        shell: pwsh
        run: |
          if ($env:GITHUB_EVENT_INPUTS_TAG_NAME) {
            echo "TAG_NAME=$env:GITHUB_EVENT_INPUTS_TAG_NAME" | Out-File -FilePath $env:GITHUB_ENV -Append
          } elseif ($env:GITHUB_REF -like 'refs/tags/*') {
            $tagName = $env:GITHUB_REF -replace 'refs/tags/', ''
            echo "TAG_NAME=$tagName" | Out-File -FilePath $env:GITHUB_ENV -Append
          } else {
            Write-Host "ERROR: tag_name input is required when running manually."
            exit 1
          }

      - name: Build Chrome Release
        run: pwsh ./scripts/build-release.ps1 chrome

      - name: Build Edge Release
        run: pwsh ./scripts/build-release.ps1 edge

      - name: Build Firefox Release
        run: pwsh ./scripts/build-release.ps1 firefox

      - name: Create Release and Upload Artifacts
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: "Automated release for ${{ env.TAG_NAME }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset - Chrome
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Easy.Compressor-chrome.zip
          asset_name: Easy.Compressor-chrome.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Edge
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Easy.Compressor-edge.zip
          asset_name: Easy.Compressor-edge.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Firefox
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Easy.Compressor-firefox.zip
          asset_name: Easy.Compressor-firefox.zip
          asset_content_type: application/zip